Make storage configurable
qdrant/mmap-payload-storage pull request #30
Opened 2024-11-04 18:35 UTC by coszio

Introduces `StorageOptions` and `StorageConfig` to depend less on constants, and be able to configure different sizes of:
- block size
- region size
- page size

2024-11-05 16:15 UTC, agourlay commented on src/config.rs
> +pub struct StorageOptions {
What does having two different types bring exactly?

I feel like `StorageOptions` is more a builder for `StorageConfig` at this point.

Maybe it could do additional validation with a `new` function to make sure that the values play well together.

2024-11-05 17:08 UTC, coszio commented on src/config.rs
> +pub struct StorageOptions {
Yes, the idea is to use the Options as interface only.

Validating the input is a good idea.

2024-11-07 14:38 UTC, agourlay commented on src/blob_store.rs
> +        let config_path = base_path.join(CONFIG_FILENAME);
needs to be added to `files` for snapshot

2024-11-07 14:41 UTC, agourlay commented on src/blob_store.rs
> +        serde_json::to_writer_pretty(file, &config).unwrap();
we need an atomic write here https://github.com/qdrant/qdrant/pull/5039/files

2024-11-07 14:44 UTC, agourlay commented on src/blob_store.rs
> +        serde_json::to_writer_pretty(file, &config).unwrap();
also maybe better to save last as a signal that everything has been done before

then opening storage, look at storage first

2024-11-07 14:48 UTC, agourlay requested changes
please see comments

2024-11-07 16:04 UTC, agourlay approved these changes

2024-11-07 16:31 UTC, merged